%lang starknet

from immutablex.starknet.token.erc721.presets.ERC721_Full import (
    constructor,
    supportsInterface,
    name,
    symbol,
    balanceOf,
    ownerOf,
    getApproved,
    isApprovedForAll,
    contractURI,
    tokenURI,
    royaltyInfo,
    getDefaultRoyalty,
    hasRole,
    getRoleAdmin,
    getMinterRole,
    getBurnerRole,
    approve,
    setApprovalForAll,
    transferFrom,
    safeTransferFrom,
    setBaseURI,
    setTokenURI,
    resetTokenURI,
    setContractURI,
    setDefaultRoyalty,
    setTokenRoyalty,
    resetDefaultRoyalty,
    resetTokenRoyalty,
    permissionedMint,
    permissionedBurn,
    grantRole,
    revokeRole,
    renounceRole,
)
