---
name: Lint, Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  init:
    name: Cancel Previous Runs on Branch
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs on Branch
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  prettier:
    name: "Test TS Prettier Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          prettier_options: "--write **/*.ts"

  cairo-format-test:
    name: Test Cairo Code Formatted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Setup
        run: |
          python -m pip install --upgrade pip
          npm run setup
      - name: Run Cairo Format
        run: |
          find . -type f -name "*.cairo" -exec bash -c 'i="$1"; poetry run cairo-format $i | diff $i - >/dev/null 2>&1 && echo $i _PASSED_TEST_ || echo $i _FAILED_TEST_ | tee -a cairo-format-test.log' bash {} \;
          test -f cairo-format-test.log && echo Failed cairo-format test && exit 1
          echo "Passed Cairo Format test"

  hardhat-test:
    name: Run Hardhat Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Setup
        run: npm run setup
      - name: Run Tests
        run: npm run test
